### ISSUE TITLE
USER STORY: Anonymity

### ISSUE THREAD

**Issue by Catalaunensis** [Matthieu-Arn/love-running_mha#2]
As a **runner**, I can **choose to hide my identity when giving feedback**, so that **I remain anonymous**

### Acceptance criteria
- The option should be provided as a checkbox
- The checkbox should be “checked” by default
- The option should appear next to the submit button
- After submitting the default submission confirmation should be adjusted to include the user name.

### Tasks
- [ ] Update the view: the poll design (HTML and CSS) to include the checkbox and to show the name of the submitter
- [ ] Create a new field in the model to track the username
- [ ] Update the controller functions
- [ ] Update unit test scripts
- [ ] Test the functionality
